name: Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: 'pages'
  cancel-in-progress: true

jobs:
  build-emscripten:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - uses: HandcrankEngine/install-emscripten-package@v0.1.0

      - name: Install HandcrankEngine
        run: |
          git clone https://github.com/HandcrankEngine/HandcrankEngine.git

      - name: Build WebGL
        run: |
          build-demo() {
            NAME="${1}"
            emcc -std=c++17 -Os -o "demos/${NAME}/${NAME}.js" "demos/${NAME}/${NAME}.cpp" \
                -I./HandcrankEngine/include \
                -s USE_SDL=2 -s USE_SDL_IMAGE=2 -s SDL2_IMAGE_FORMATS='["png", "svg"]' -s USE_SDL_TTF=2 -s USE_SDL_MIXER=2 \
                -s MODULARIZE=1 -s EXPORT_NAME="${NAME}Module" --pre-js ./bin/sdl-mod.js
          }
          build-demo "demo"
          build-demo "animation"
          build-demo "drawRectRenderer"
          build-demo "simpleEventLoop"
          build-demo "spriteRenderer"
          build-demo "svg"
          build-demo "tiledMapSupport"

      - name: Upload artifact
        uses: actions/upload-artifact@v5
        with:
          path: ./demos
          overwrite: true

  build-web:
    runs-on: ubuntu-latest
    needs: build-emscripten
    env:
      TZ: 'America/New_York'
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Download artifact
        uses: actions/download-artifact@v6
        with:
          path: ./demos

      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: '22'

      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v5

      - name: Install dependencies
        run: npm ci

      - name: Build Site
        run: npm run build

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./build

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: [build-emscripten, build-web]
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
